apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc01
  labels:
    app: mc01
spec:
  selector:
    matchLabels:
      app: mc01
  replicas: 1
  template:
    metadata:
      labels:
        app: mc01
    spec:
      containers:
      - name: mc01
        image: memcached
        ports:
        - name: mc01-port
          containerPort: 11211
